--- #YAML:1.0
name:               Text-TFIDF
version:            0.02
abstract:           Perl extension for computing the TF-IDF measure
author:
    - Leigh Metcalf <leigh@fprime.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
